# Generated by Django 4.1.4 on 2022-12-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='itStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('hall', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('batch', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=20)),
                ('sem', models.CharField(max_length=30)),
            ],
        ),
    ]
